### ISSUE TITLE
empty values in image card

### ISSUE THREAD

**Issue by etepes** [cestef/spotify-card#10]
⬇⬇⬇⬇⬇⬇⬇⬇

**Comment by etepes** [comment]
So i have a kind of problem/bug idk, i have read the hole docs but i can't find a fix, Title and Time remaining doesnt show in my card, i don't know if this is an issue of the npm or by my side but i need a solution ASAP, ty:).

Here is my code: 
![ss1](https://user-images.githubusercontent.com/87408507/169600662-21d3a823-19b1-4e7d-bbf9-b592325fbc57.JPG)


PSDT:  by the way, my code doesn't throw me me an error, just doesn't show anything on the card:
![ss2](https://user-images.githubusercontent.com/87408507/169601011-350aac3b-a310-4d2e-8651-be5ce8cc2d44.JPG)

**Comment by cestef** [comment]
I think you're using too many useless parameters, what does trackurl stand for ?

**Comment by etepes** [comment]
> I think you're using too many useless parameters, what does trackurl stand for ?

To get the id of the song:
https://open.spotify.com/track/7yq4Qj7cqayVTp3FF9CWbm
this: 7yq4Qj7cqayVTp3FF9CWbm is the ID track, i defined like this: TRACKURL

**Comment by cestef** [comment]
Then you don't need to set title and artist manually, the package takes care of this. Same for the cover

**Comment by cestef** [comment]
This is my bad, I forgot to update the docs with the latest API... title and artist go to songData and not the root options object

**Comment by cestef** [comment]
This has been fixed. See https://docs.cstef.dev/docs/spotify-card/interfaces/GenerateOptions

**Comment by etepes** [comment]
> This is my bad, I forgot to update the docs with the latest API... title and artist go to songData and not the root options object

Ight ima check this out. 
Btw, what about the remaining time under the progressbar, where can i get that value? because it doesn't show up on my Spotify card either

**Comment by cestef** [comment]
No idea, this works on my end, please check that your values are correctly formatted

**Comment by cestef** [comment]
(numbers - in milliseconds)

**Comment by etepes** [comment]
> No idea, this works on my end, please check that your values are correctly formatted

As you can see in the image I uploaded, I manually put a number in currentTime to see if it was a bug or something, but it doesn't shows on my spotify card. 
I'll try with the new docs when i get home and I'll give you a feedback, thank you.
