### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by uSebazz** [cestef/spotify-card#9]
Progress bar is enabled, but currentTime or totalTime not specified

code:
```ts
const img = await generate({
			url: queue.current?.uri as string,
			platform: 'spotify',
			songData: {
				title: queue.current!.title,
				cover: `https://img.youtube.com/vi/${
					queue.current!.identifier
				}/maxresdefault.jpg`,
				artist: queue.current!.author,
			} as CustomSongData,
			progressBar: true,
			currentTime: player?.position as number,
			totalTime: queue.current?.length as number,
		})
```

**Comment by cestef** [comment]
Can you provide the full error ?

**Comment by uSebazz** [comment]
> Can you provide the full error ?

wait, you have a discord server?

**Comment by cestef** [comment]
unfortunately no

**Comment by uSebazz** [comment]
> unfortunately no

Ok, wait I send you the complete error

**Comment by uSebazz** [comment]
> unfortunately no

Ok, wait I send you the complete error

**Comment by uSebazz** [comment]
![image](https://user-images.githubusercontent.com/90474850/161434330-c838b8d1-5e5e-4e14-8d7e-95bc680e440a.png)

**Comment by cestef** [comment]
Hi back, sorry for the late response, I was busy lately. This is because totalTime or currentTime is undefined. The problem is most likely on your side.

**Comment by uSebazz** [comment]
> Hi back, sorry for the late response, I was busy lately. This is because totalTime or currentTime is undefined. The problem is most likely on your side.

I think, let me see

**Comment by uSebazz** [comment]
> > Hi back, sorry for the late response, I was busy lately. This is because totalTime or currentTime is undefined. The problem is most likely on your side.
> 
> I think, let me see

Yeah, is that thks!
